# Generated by Django 6.0.2 on 2026-04-06 09:27

# pyrefly: ignore [missing-import]
import django.utils.timezone
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosubmission',
            name='expression_breakdown',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='videosubmission',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Tanggal pembelajaran'),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='day',
            field=models.CharField(default='Senin', editable=False, max_length=20),
        ),
    ]
