# Generated by Django 6.0.2 on 2026-04-07 07:41

# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_videosubmission_expression_breakdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosubmission',
            name='subject',
            field=models.CharField(choices=[('english', 'English'), ('bahasa_indonesia', 'Bahasa Indonesia'), ('science', 'Science'), ('math', 'Math')], max_length=50),
        ),
    ]
