# Generated by Django 6.0.2 on 2026-05-21 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_videosubmission_ground_truth_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosubmission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('principal', 'Principal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='day',
            field=models.CharField(default='Monday', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Learning date'),
        ),
    ]
